### ISSUE TITLE
Materials hierarchy is wrong if a goup contains only sub-folders

### ISSUE THREAD

**Issue by LeBenLeBen** [fbrctr/fabricator-assemble#21]
I saw some pull-requests about folders so it may have already been addressed but I’m not sure so I prefer to report it.

Imagine you have such hierarchy in your materials:

```
└── materials
    ├── components
    │   ├── forms
    │   │   ├── fields.html
    │   │   └── buttons.html
    │   └── media.html
    └── structures
        └── lists
            ├── inline-list.html
            └── stacked-list.html
```

The `components` folder will be assembled perfectly. However, the `structures` level disappear and `lists` is built at root because it contains no html files, only sub-folders. Since the dedicated file to list those materials is `views/structures.html` and not `views/lists.html`, any link to this section result in a 404.

**Comment by LukeAskew** [comment]
Interesting. Took me a while to figure this one out, but I think this covers it: https://github.com/fbrctr/fabricator-assemble/commit/191c1372ca60fc02a4cbfa0fe59f5b988a7597b5


Looks like it due to this logic: https://github.com/fbrctr/fabricator-assemble/blob/b5b1f08830cd131071ad348d8d0bc04dc943363a/index.js#L274

This first loop creates an array of directory names that's used to determine if the material is part of a "collection" (sub-folder).

[L284](https://github.com/fbrctr/fabricator-assemble/blob/b5b1f08830cd131071ad348d8d0bc04dc9
43363a/index.js#L284) does the check again the dir array, but the dir array doesn't contain `structures` because of the way I deconstruct the paths.

**Comment by LeBenLeBen** [comment]
Thanks Luke, it is much better now!

However there seems to be a bug when the main folder (structures) doesn’t include any file. It’s name in the interface is not "structures" but the name of the first sub-folder (forms in my case).

![Screeshot](https://cloud.githubusercontent.com/assets/793344/9351789/902c0f14-465c-11e5-819f-c25920bc4bab.png)

**Comment by LukeAskew** [comment]
Should be fixed now. I'll put together a release after I address a handful of other issues.
