### ISSUE TITLE
Layouts and data usage

### ISSUE THREAD

**Issue by quentinbutz** [fbrctr/fabricator-assemble#39]
Hey, sorry if this is a stupid question but I'm a bit confused as to the usage of Layouts. I'm trying to get my head around using Fabricator in a more data driven way.

What are they used for if all of the content is simply inserted into the body? It might just be a terminology thing, but when I think of layouts I'm thinking of maybe a single, dual etc grid layout and being able to specify the content for the main section, aside etc

Thanks
Chris

**Comment by quentinbutz** [comment]
Also, again I may be missing something obvious here but...

I've defined a bunch of components, let's use buttons as an example. I'm building a page and I want a button, great, {{> button}} pop that button in, and it has a space for the link text, so I define that at the top:

---
link: button text
---

...but, now I pop a second button in the page, how do I put different text in that button?

Can I not? If so, what's the point of defining the components? 

Thanks
Chris

**Comment by quentinbutz** [comment]
Update:

Second question is solved, got it working with:

`<a class="btn {{ btnclass }}" href="#">{{ btnlink }}</a>`
`{{> button btnclass="btn--pri" btnlink="this is a button" }}`

**Comment by LukeAskew** [comment]
What you're describing would be a "view". Layouts are meant to be the page container. They are helpful if you need to provide pages with alternate container/wrapper/header/footer markup. 

For instance, I just added a layout to one of my Fabricator project that is for pages embded via an iFrame. I need all the same components, but different `<head>` data and no global header or footer. I created an `iframe.html` layout and referenced it in my view.

Its also helpful to think of Fabricator's views/layouts as more of a prototyping tool rather than a static site generator. They are meant to be blueprints for how the components fit together.
